//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlEditor.Properties.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All keys in this page are in use.
        /// </summary>
        public static string allKeysInThisPageAreInUse {
            get {
                return ResourceManager.GetString("allKeysInThisPageAreInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin has made this column read only.
        /// </summary>
        public static string aPluginHasMadeReadOnly {
            get {
                return ResourceManager.GetString("aPluginHasMadeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error Message.
        /// </summary>
        public static string databaseErrorMessage {
            get {
                return ResourceManager.GetString("databaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to use deep delete?.
        /// </summary>
        public static string deepDeleteAreYouSure1 {
            get {
                return ResourceManager.GetString("deepDeleteAreYouSure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep delete is dangerous! When you delete a row, it deletes the chosen row AND all its children, grandchildren, etc..
        /// </summary>
        public static string deepDeleteAreYouSure2 {
            get {
                return ResourceManager.GetString("deepDeleteAreYouSure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display key value array must be unique..
        /// </summary>
        public static string displayKeyValueArrayMustBeUnique {
            get {
                return ResourceManager.GetString("displayKeyValueArrayMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to merge duplicate display key rows?.
        /// </summary>
        public static string doYouWantToMergeDuplicateKeyRows {
            get {
                return ResourceManager.GetString("doYouWantToMergeDuplicateKeyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to see these rows?.
        /// </summary>
        public static string doYouWantToSeeTheseRows {
            get {
                return ResourceManager.GetString("doYouWantToSeeTheseRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each of the displayed rows has an empty foreign keys..
        /// </summary>
        public static string eachOfDisplayedRowsHasEmptyFK {
            get {
                return ResourceManager.GetString("eachOfDisplayedRowsHasEmptyFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap end_arrow_32 {
            get {
                object obj = ResourceManager.GetObject("end-arrow-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Connection String. Numbers in brackets {} represent values given above.  Use {3} for password..
        /// </summary>
        public static string EnterConnectionStringDirections {
            get {
                return ResourceManager.GetString("EnterConnectionStringDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a user name or choose a connection string without {2}..
        /// </summary>
        public static string enterUserNameOrNoUserString2 {
            get {
                return ResourceManager.GetString("enterUserNameOrNoUserString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error backing up the database..
        /// </summary>
        public static string errorBackingUpDatabase {
            get {
                return ResourceManager.GetString("errorBackingUpDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in updating table {0}..
        /// </summary>
        public static string errorInUpdatingTable0 {
            get {
                return ResourceManager.GetString("errorInUpdatingTable0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening connection..
        /// </summary>
        public static string errorOpeningConnection {
            get {
                return ResourceManager.GetString("errorOpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything O.K. No duplicates!.
        /// </summary>
        public static string EverythingOkNoDuplicates {
            get {
                return ResourceManager.GetString("EverythingOkNoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first column must be the primary key..
        /// </summary>
        public static string firstColumnMustBePrimaryKey {
            get {
                return ResourceManager.GetString("firstColumnMustBePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconmonstr_arrow_32_LEFT {
            get {
                object obj = ResourceManager.GetObject("iconmonstr-arrow-32 LEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconmonstr_arrow_32_OneLEFT {
            get {
                object obj = ResourceManager.GetObject("iconmonstr-arrow-32 OneLEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconmonstr_arrow_32_OneRight {
            get {
                object obj = ResourceManager.GetObject("iconmonstr-arrow-32 OneRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconmonstr_arrow_32_RIGHT {
            get {
                object obj = ResourceManager.GetObject("iconmonstr-arrow-32 RIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are no rows displayed, there are no empty foreign keys..
        /// </summary>
        public static string ifNoDisplayedRowsNoEmptyFK {
            get {
                return ResourceManager.GetString("ifNoDisplayedRowsNoEmptyFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Filter not set.
        /// </summary>
        public static string MainFilterNotSet {
            get {
                return ResourceManager.GetString("MainFilterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF.
        /// </summary>
        public static string mainFilterShort {
            get {
                return ResourceManager.GetString("mainFilterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pass test before O.K. button is enabled.
        /// </summary>
        public static string MustPassTestBeforeOKButton {
            get {
                return ResourceManager.GetString("MustPassTestBeforeOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select a value.
        /// </summary>
        public static string mustSelectAvalue {
            get {
                return ResourceManager.GetString("mustSelectAvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        public static string narrow {
            get {
                return ResourceManager.GetString("narrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous connection string..
        /// </summary>
        public static string NoPreviousConnectionSet {
            get {
                return ResourceManager.GetString("NoPreviousConnectionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rows modified.
        /// </summary>
        public static string numberOfRowsModified {
            get {
                return ResourceManager.GetString("numberOfRowsModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a string that has &apos;Database={1}&apos; in it.
        /// </summary>
        public static string pleaseChooseDatabaseString {
            get {
                return ResourceManager.GetString("pleaseChooseDatabaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for {0}.
        /// </summary>
        public static string pleaseSelectAvalueFor0 {
            get {
                return ResourceManager.GetString("pleaseSelectAvalueFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key must be an integer.
        /// </summary>
        public static string primaryKeyMustBeInt {
            get {
                return ResourceManager.GetString("primaryKeyMustBeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows that should be merged: {0}.
        /// </summary>
        public static string rowsThatShouldBeMerged0 {
            get {
                return ResourceManager.GetString("rowsThatShouldBeMerged0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected row is not the value of a foreign key..
        /// </summary>
        public static string selectedRowIsNotValueOfForeignKey {
            get {
                return ResourceManager.GetString("selectedRowIsNotValueOfForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select exactly one row in the table.
        /// </summary>
        public static string selectExactlyOneRow {
            get {
                return ResourceManager.GetString("selectExactlyOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select exactly two row in the table.
        /// </summary>
        public static string selectExactlyTwoRows {
            get {
                return ResourceManager.GetString("selectExactlyTwoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select row to delete.
        /// </summary>
        public static string selectRowToDelete {
            get {
                return ResourceManager.GetString("selectRowToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tess passed!.
        /// </summary>
        public static string testPassed {
            get {
                return ResourceManager.GetString("testPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        public static string wide {
            get {
                return ResourceManager.GetString("wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows, Page {1}.
        /// </summary>
        public static string XrowsPageY {
            get {
                return ResourceManager.GetString("XrowsPageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have this object in your database!.
        /// </summary>
        public static string youAlreadyHaveThisObjectInDatabase {
            get {
                return ResourceManager.GetString("youAlreadyHaveThisObjectInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Server name.
        /// </summary>
        public static string youMustEnterServerName {
            get {
                return ResourceManager.GetString("youMustEnterServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to merge rows in {0} first..
        /// </summary>
        public static string youNeedtoMergeRowIn0 {
            get {
                return ResourceManager.GetString("youNeedtoMergeRowIn0", resourceCulture);
            }
        }
    }
}
