//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlEditor.TranscriptPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlEditor.TranscriptPlugin.Properties.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and it will update the credits, QPA, and lastTerm based on the transcript table..
        /// </summary>
        public static string andUpdateQPAbasedOnTranscriptTable {
            get {
                return ResourceManager.GetString("andUpdateQPAbasedOnTranscriptTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print English Transcript.
        /// </summary>
        public static string btnEnglishPrintTranscript_Text {
            get {
                return ResourceManager.GetString("btnEnglishPrintTranscript.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Course Grade Sheet.
        /// </summary>
        public static string btnPrintCourseGrades_Text {
            get {
                return ResourceManager.GetString("btnPrintCourseGrades.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Course Role.
        /// </summary>
        public static string btnPrintCourseRole_Text {
            get {
                return ResourceManager.GetString("btnPrintCourseRole.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Transcript.
        /// </summary>
        public static string btnPrintTranscript_Text {
            get {
                return ResourceManager.GetString("btnPrintTranscript.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Role.
        /// </summary>
        public static string courseRole {
            get {
                return ResourceManager.GetString("courseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Credit-QPA-LastTerm updated: {1} students..
        /// </summary>
        public static string CreditsQPALtUpdatedAndCount {
            get {
                return ResourceManager.GetString("CreditsQPALtUpdatedAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the file in Word?.
        /// </summary>
        public static string doYouWantToOpenInWord {
            get {
                return ResourceManager.GetString("doYouWantToOpenInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the StudentDegrees Table?.
        /// </summary>
        public static string doYouWantToUpdateStDeTable {
            get {
                return ResourceManager.GetString("doYouWantToUpdateStDeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR filling transcript table: {0}.
        /// </summary>
        public static string ErrorFillingTranscriptTable0 {
            get {
                return ResourceManager.GetString("ErrorFillingTranscriptTable0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Grades template.
        /// </summary>
        public static string lblCourseGradesTemplate_Text {
            get {
                return ResourceManager.GetString("lblCourseGradesTemplate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Role Template :.
        /// </summary>
        public static string lblCourseRoleTemplate_Text {
            get {
                return ResourceManager.GetString("lblCourseRoleTemplate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Folder.
        /// </summary>
        public static string lblDocumentFolder {
            get {
                return ResourceManager.GetString("lblDocumentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Transcript Template.
        /// </summary>
        public static string lblEnglishTranscriptTemplate {
            get {
                return ResourceManager.GetString("lblEnglishTranscriptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        public static string lblLanguage_Text {
            get {
                return ResourceManager.GetString("lblLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders and Templates.
        /// </summary>
        public static string lblOptions_Text {
            get {
                return ResourceManager.GetString("lblOptions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After changing interface language, please close and restart this program..
        /// </summary>
        public static string lblRestartMsg_Text {
            get {
                return ResourceManager.GetString("lblRestartMsg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Folder :.
        /// </summary>
        public static string lblTemplateFolder_Text {
            get {
                return ResourceManager.GetString("lblTemplateFolder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript Template :.
        /// </summary>
        public static string lblTranscriptTemplate_Text {
            get {
                return ResourceManager.GetString("lblTranscriptTemplate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Word.
        /// </summary>
        public static string openInWord {
            get {
                return ResourceManager.GetString("openInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Course in {0} table (a descendant of the {1} table).
        /// </summary>
        public static string selectCourseInTable01 {
            get {
                return ResourceManager.GetString("selectCourseInTable01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select exactly one row in the table.
        /// </summary>
        public static string selectExactlyOneRow {
            get {
                return ResourceManager.GetString("selectExactlyOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 1 row in the {0} table or {1} table.
        /// </summary>
        public static string selectOneRowinTable0or1 {
            get {
                return ResourceManager.GetString("selectOneRowinTable0or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Student in {0} table (a descendant of the {1} table).
        /// </summary>
        public static string selectStudentInTable01 {
            get {
                return ResourceManager.GetString("selectStudentInTable01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentDegree table updated.{0}Status updated: {1} students..
        /// </summary>
        public static string StDeTableUpdatedAndCount {
            get {
                return ResourceManager.GetString("StDeTableUpdatedAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string tabActions_Text {
            get {
                return ResourceManager.GetString("tabActions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string tabExit_Text {
            get {
                return ResourceManager.GetString("tabExit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string tabOptions_Text {
            get {
                return ResourceManager.GetString("tabOptions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string tabRequirements_Text {
            get {
                return ResourceManager.GetString("tabRequirements.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string tabStudent_Text {
            get {
                return ResourceManager.GetString("tabStudent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript.
        /// </summary>
        public static string tabTranscript_Text {
            get {
                return ResourceManager.GetString("tabTranscript.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will update the StudentDegrees Table studentStatus based on the StudentStatusHistory table;.
        /// </summary>
        public static string thiswillUpdateTheStudentDegreesTable {
            get {
                return ResourceManager.GetString("thiswillUpdateTheStudentDegreesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        public static string toolStripBtnNarrow_Text {
            get {
                return ResourceManager.GetString("toolStripBtnNarrow.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        public static string toolStripBtnNarrowWide_Text {
            get {
                return ResourceManager.GetString("toolStripBtnNarrowWide.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update StudentDegrees Table.
        /// </summary>
        public static string updateStudentDegreesTable {
            get {
                return ResourceManager.GetString("updateStudentDegreesTable", resourceCulture);
            }
        }
    }
}
